config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }, skip: [:registrations, :login]
  # omniauth_callbacks points to Users::OmniauthCallbacks

  resources :travel_notes, only: [:index, :create, :show, :destroy, :edit, :update] 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/travel_note.rb
class TravelNote < ApplicationRecord
  paginates_per 5
  belongs_to :travaler, class_name: "User"

  # validations
  validates :city, presence: { message: 'City is required' }
  validates :body, length: { in: 10..500, message: "Your note must have between 10 to 500 words!" }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :travel_notes, foreign_key: :travaler_id, dependent: :destroy 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         #:recoverable,
         :rememberable, 
         :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2]

  def self.from_omniauth(auth)
    # find the existing user; if one does not exist create
    # first_or_create automatically sets user.providr and user.uid with the appropriate values
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20] # create password for user who  in with google
      user.username = auth.info.name # assuming auth.info.name exists 
    end 
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  #before_action :authenticate_user!

  def index 
    if current_user 
      @greetings = { "welcome": "Hello #{current_user.username}" }
    else 
      @greetings = { "welcome": "This is Traveler Diary" }
    end 
  end

end

app/controllers/travel_notes_controller.rb
class TravelNotesController < ApplicationController

  before_action :authenticate_user!
  before_action :call_city, only: [:create, :update]

  def index
    @travel_notes = current_user.travel_notes.order('created_at DESC').page(params[:page] || 0)
  end

  def create 
    params = travel_note_params.merge({
      current_temperature: @current_temperature
    })
    @travel_note = current_user.travel_notes.new(params)
    respond_to do |format|
      if @travel_note.save
        format.js 
        format.html  { redirect_to travel_notes_path, flash: { success: 'Travel note has been created!' } }
      else 
        format.html  { redirect_to travel_notes_path, flash: { error: @travel_note.errors.messages[:body].first } }
      end
    end   
  end

  def destroy
    @travel_note = current_user.travel_notes.find_by!(id: params[:id])

    respond_to do |format|
      if @travel_note.destroy
        format.js 
        format.html { render :index, flash: { info: 'Travel Note has been deleted!' } }
      else 
        format.html { redirect_to root_url }
      end
    end 
  end

  def edit
    @travel_note = current_user.travel_notes.find_by!(id: params[:id])
  end

  def update
    @travel_note = current_user.travel_notes.find_by(id: params[:id])

    @updated_note = @travel_note.update(
      {
        city: travel_note_params[:city],
        body: travel_note_params[:body],
        current_temperature: @current_temperature
      }.compact
    )

    if @updated_note
      redirect_to travel_notes_path, flash: { success: 'Travel note has been changed!' } 
    else 
      render :edit
    end
  end

  private 

  def travel_note_params
    params.require(:travel_note).permit(:body, :city, :current_temperature)
  end

  def call_city
    weather_api = ::WeatherCallService.new(travel_note_params).call_weather
    if weather_api.success?
      @current_temperature = weather_api["main"]["temp"]
    else
      redirect_to travel_notes_path, flash: { error: weather_api["message"] }
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  # enables rememberable option 
  include Devise::Controllers::Rememberable

  def google_oauth2
    # all information retrieved from Google by OmniAuth is available 
    # as a hash at request.env["omniauth.auth"]
    
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      flash[:info] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
      remember_me(@user) # remembers user for 2 minutes 
      # event: :authentication causes Warden(underlying Devise) to trigger 
      # any callbacks defined with Warden::Manager.after_authentication block
      # pretty useful, ex. store additional data about user behaviour 
    else # if something went wrong 
      session['devise.google_data'] = request.env['omniauth.auth'].except('extra') # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url, flash: { error: @user.errors.full_messages.join("\n") }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_func(type)
    case type 
    when 'error'
      'alert-danger'
    when 'info'
      'alert-info'
    when 'success'
      'alert-success'
    when 'notice'
      'alert-info'
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/travel_note_helper.rb
module TravelNoteHelper
end

app/views/home/index.html.erb
<div class='jumbotron'>
  <h1><%= @greetings[:welcome] %></h1>
  <div class="row">
    <% if current_user %>
      <%= button_to 'Log out', destroy_user_session_path, method: :delete %>
      <%= button_to 'Travel notes', travel_notes_path, method: :get %>
    <% else %>
      <%= button_to 'Login with google!', user_google_oauth2_omniauth_authorize_path, method: :get %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="google-site-verification" content="dHXbIdZPtktlF7EiPkQkQyXNtNu11bmZ_fFS_AI_t24" />
    <title>TravelDiary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>

  <body>
    <%= render partial: 'shared/flash' %>
    <%= yield %>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>

</html>

app/views/shared/_flash.html.erb
<div>
  <% flash.each do |key, value| %>
    <div class="alert <%= flash_func(key) %>">
      <%= value %>
    </div>
  <% end %>
</div>

app/views/travel_notes/_form.html.erb
<div class='row'>
  <div class='col-4'>
    <h1>Form</h1>
    <%= form_with model: TravelNote.new, remote: true do |note| %>
      <%= note.text_area :city, placeholder: 'City' %>
      <%= note.text_area :body, size: "70x5", placeholder: 'Note' %>
      <%= note.submit 'Save', class: 'submit' %> 
    <% end %>
    <%= button_to 'Home', root_path, method: :get %>
  </div>
</div>

app/views/travel_notes/_travel_note.html.erb
<tr class='<%= travel_note.id%>'>
  <td style="width:20%"><%= travel_note.updated_at.strftime('%d.%m.%y %H:%M') %></td>
  <td style="width:50%"><%= travel_note.city %> <%= travel_note.current_temperature %>&#8451; </td>
  <td style="width:15%"><u><%= link_to 'Edit', edit_travel_note_path(travel_note) %></u></td>
  <td style="width:15%">
    <u><%= link_to 'Delete', travel_note_path(travel_note), method: :delete, remote: true %></u>
  </td>
</tr>
<tr class='bg-active <%= travel_note.id %>'>
  <td colspan="4"><%= travel_note.body %></td>
</tr>

app/views/travel_notes/_travel_note_errors.html.erb
<% if @travel_note.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@travel_note.errors.count, "error") %> prohibited this article from being saved:</h2>
    <ul>
      <% @travel_note.errors.each do |error| %>
        <li><%= error %></li>
      <% end %> 
    </ul>
  </div>
<% end %>

app/views/travel_notes/create.js.erb
var clicks = $('.submit').click();
if (clicks) {
  $('table#travel-notes tbody').prepend("<%= j render @travel_note %>");
}

app/views/travel_notes/destroy.js.erb
$('.<%= @travel_note.id %>').remove()

app/views/travel_notes/edit.html.erb
<div class='container d-flex justify-content-center align-items-center'>
  <div class='row'>
    <div class='col-4'>
      <% if @travel_note.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@travel_note.errors.count, "error") %> prohibited this article from being saved:</h2>
          <ul>
            <% @travel_note.errors.each do |error| %>
              <li><%= error %></li>
            <% end %> 
          </ul>
        </div>
      <% end %>
      <h1>Edit travel note!</h1>
      <%= form_with model: @travel_note  do |note| %>
        <%= note.text_area :city, placeholder: 'City' %>
        <%= note.text_area :body, size: "70x5", placeholder: 'Note' %>
        <%= note.submit 'Edit', class:'submit' %>
      <% end %>
      <%= button_to "Go back", travel_notes_path, method: :get %>
    </div>
  </div>
</div>

app/views/travel_notes/index.html.erb
<div class='container'>
  <%= render partial: 'form' %>
  <div class='row'>
    <div class='col-6'>
      <% if @travel_notes.nil? %>
        <h1>Add your first note!</h1>
      <% else %>
        <h1> Old notes</h1>
      <% end %>
      <table class="table" id='travel-notes'>
        <tbody>
          <%= render partial: 'travel_note', collection: @travel_notes %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/travel_notes/show.html.erb
<div class='jumbotron'>
  <div class="row">
    <div class='col-md-3'>
      <p><%= @travel_note.body %></p>
    </div>
    <div class='col-md-3'>
      <p><%= @travel_note.city %></p>
    </div>
    <div class='col-md-3'>
      <p><%= @travel_note.current_temperature %>&#8451;</p>
    </div>
  </div>
</div>